Metric collection compatibility enhancement
eth-educators/eth-docker pull request #1621
Opened 2023-11-11 02:22 UTC by aliask

### Change overview
- Increased default polling rate to 15s
- Manually reduced the price-check poll rates to 5m, no point hammering the APIs
- Allow override of job name and polling interval via Docker labels

### Explanation
Eth-docker currently does not set the polling configs, so it uses the default values (1 minute interval).

Several publicly shared Grafana dashboards expect Prometheus metrics to be available at a higher rate than what `eth-docker` provides, so importing these dashboards into Grafana causes some widgets to display "No Data".

These values were taken from the [Rocketpool config](https://github.com/rocket-pool/smartnode-install/blob/master/install/prometheus.tmpl), but the official [lighthouse-metrics](https://github.com/sigp/lighthouse-metrics/blob/master/prometheus/prometheus.yml) config also does, and [geth](https://geth.ethereum.org/docs/monitoring/dashboards#setting-up-prometheus) suggests 10s.

I've also added some extra config overrides to set the job name and poll interval via Docker labels. If these labels are omitted it still defaults to the compose service name.

In my case, this was done for compatibility with the Rocketpool dashboard as they name their jobs differently service name, but there may be other situations where this would be helpful.

I know that the polling settings can be overriden via a `custom-prom.yml` file, however the job name and individual container interval settings cannot (as far as I understand).

The increased polling rate will give users higher resolution metrics as a bonus, and the additional load on resources should not be significant.

2023-11-12 03:57 UTC, aliask commented
I've added a few new features:
- Uses `yq` tool to perform a merge of the default and custom configs. [Ref](https://mikefarah.gitbook.io/yq/operators/multiply-merge#merge-appending-arrays)
- Rootless configs now also use a folder, `rootless.d` for their scrape targets
- Configuration is back to being regenerated at each startup instead of at build-time
- A new `.env` setting has been added to allow bypassing config generation, and using `custom-prom.yml` as a standalone configuration file

I'm not so sure about that last one - the other features should make the configuration extensible enough for 99% of users.

2023-11-18 12:13 UTC, yorickdowne requested changes

2023-11-18 12:13 UTC, yorickdowne commented on prometheus/global-prom.yml
> +global:
As discussed, please move the `global:` section into `custom-prom.yml.sample` so that it remains flexible for users. I'll add code to `./ethd update` to move the custom-prom.yml.sample contents into custom-prom.yml if the latter is empty.

2023-11-18 12:13 UTC, yorickdowne commented on grafana-rootless.yml
> -  cryptowat-exporter:
This is used by some dashboards afaik. Why the removal?

2023-11-18 12:13 UTC, yorickdowne commented on prometheus/docker-entrypoint.sh
> +    if [ -s custom-prom.yml ]; then
What are you gaining by using yq here instead of just doing a cat to the end of prometheus.yml?

I am wondering whether the original method is better UX and also makes it obvious what the scrape intervals are, as long as custom-prom.yml contains those.

2023-11-18 12:13 UTC, yorickdowne commented on prometheus/Dockerfile
> +COPY ./docker-entrypoint.sh /
Into /usr/local/bin/ to match what other locally-built containers do?

2023-11-18 12:13 UTC, yorickdowne commented on prometheus/docker-entrypoint.sh
> +/bin/prometheus "$@" --config.file="${__config_file}"
Add an `exec` here so `/bin/prometheus` receives `SIGINT` and `SIGTERM`

2023-11-18 12:13 UTC, yorickdowne commented on prometheus/docker-entrypoint.sh
> +  if [ -s custom-prom.yml ]; then
This gets me `No custom configuration detected` even when there is one. Likely needs to be `if [ -s /etc/prometheus/custom-prom.yml ]` and then likewise use that path for the `yq` further down.

2023-11-18 23:21 UTC, aliask commented on prometheus/docker-entrypoint.sh
> +  if [ -s custom-prom.yml ]; then
I've updated the script to `cd /etc/prometheus` at the top, and used all relative paths for the preparation steps.

I've kept it so that Prometheus gets started with the absolute path for the prepared config file.

Tested this working with `grafana.yml` (not rootless) and it's looking OK here.

2023-11-25 11:58 UTC, yorickdowne approved these changes

2023-11-25 11:58 UTC, yorickdowne commented
Works well here, both my global external labels as well as the remote write are preserved. Merging. Thank you!

2023-11-25 11:58 UTC, merged