Fix: Broken `Lido DV Exit` and `Lido validator ejector` when a secondery CL client is added to `Charon`
eth-educators/eth-docker pull request #1950
Opened 2024-10-03 12:22 UTC by cnupy

Adding a secondary CL node endpoint to the `OBOL_CL_NODE` variable breaks the `validator-ejector` and `lido-dv-exit` services because they don't support fallback endpoints.

This PR introduces an additional environment variable `OBOL_CHARON_CL_ENDPOINTS` specific to the `Charon` service, which should be used to set the CL client for the `Charon` service. Multiple endpoints can be separated by commas.

2024-10-04 08:18 UTC, yorickdowne requested changes

2024-10-04 08:18 UTC, yorickdowne commented on default.env
> +LIDO_DV_EXIT_VERSION=
Where is this variable being used?

2024-10-04 08:18 UTC, yorickdowne commented on default.env
> +OBOL_CHARON_CL_ENDPOINTS=http://consensus:5052
Add this to `__env_migrate` in `ethd` as well, so its value is kept across `ethd update`

2024-10-04 08:18 UTC, yorickdowne commented on default.env
> +OBOL_CHARON_CL_ENDPOINTS=http://consensus:5052
Increment `ENV_VERSION` below from currently `17` to `18`, so an `ethd update` will bring in the new variable you defined.

2024-10-04 10:58 UTC, cnupy commented on default.env
> +OBOL_CHARON_CL_ENDPOINTS=http://consensus:5052
> Add this to `__env_migrate` in `ethd` as well, so its value is kept across `ethd update`

Sorry, this is my first post and I have a few questions:
I need to add the variable to the `__all_vars` array to be persisted after the `ethd update` - is this correct?
But I'm not sure if there is a mechanism to initialise the value of the new variable on the first update? I'm thinking that someone who has changed the value of the `OBOL_CL_NODE` variable would want the new `OBOL_CHARON_CL_ENDPOINTS` variable to be set to the value of the `OBOL_CL_NODE` variable when it is introduced. Do you have any guidance on how to implement this?
I also noticed that in the `__all_vars` array, the name of the `OBOL_CL_NODE` variable is incorrectly written as `CL_OBOL_NODE`.

2024-10-04 11:00 UTC, cnupy commented on default.env
> +LIDO_DV_EXIT_VERSION=
> Where is this variable being used?

It's used in `lido-obol.yml` on line 88, but was missing from the `default.env`

2024-10-04 20:47 UTC, yorickdowne commented on default.env
> +LIDO_DV_EXIT_VERSION=
Oh good catch! Into `__env_migrate` as well then, please.

2024-10-04 20:50 UTC, yorickdowne commented on default.env
> +OBOL_CHARON_CL_ENDPOINTS=http://consensus:5052
Yes that's correct, it goes into `__all_vars`, which causes it to persist when `ENV_VERSION` is incremented.

Thanks for the typo catch, can you fix that while at it?

There is a mechanism to initialize. Since the variable is new, you could check for `ENV_VERSION` and if below the one you are incrementing to here, set `OBOL_CHARON_CL_ENDPOINTS` to whatever `OBOL_CL_NODE` is. You can find some sample code that does similar things in `__env_migrate`. Well, not merged yet ... take a look at the v6 enable PR.

2024-10-05 13:52 UTC, cnupy commented on default.env
> +OBOL_CHARON_CL_ENDPOINTS=http://consensus:5052
Thanks. All resolved.

2024-10-06 08:38 UTC, yorickdowne requested changes

2024-10-06 08:38 UTC, yorickdowne commented on ethd
> +    ERIGON_P2P_PORT_3 LODESTAR_HEAP SSV_DKG_PORT SIREN_PASSWORD LIDO_DV_EXIT_VERSION OBOL_CHARON_CL_ENDPOINTS)
```suggestion
    ERIGON_P2P_PORT_3 LODESTAR_HEAP SSV_DKG_PORT SIREN_PASSWORD LIDO_DV_EXIT_VERSION OBOL_CHARON_CL_ENDPOINTS )
```

2024-10-06 08:38 UTC, yorickdowne commented on ethd
> +        || [ "${__var}" = "OBOL_CHARON_CL_ENDPOINTS" ]; then
You don't expect this one to be legitimately empty, do you? I think this change can be left as it was

2024-10-06 09:53 UTC, cnupy commented on ethd
> +        || [ "${__var}" = "OBOL_CHARON_CL_ENDPOINTS" ]; then
It is empty when upgrading from a version prior to v18, so the check below never hits. As a result, the value is left at the default value in `default.env` - `http://consensus:5052` after migration. My intention was to migrate it to the value of `OBOL_CL_NODE` - what was previously used in the `lido-obol.yml` `Charon` service.

2024-10-06 10:45 UTC, yorickdowne approved these changes

2024-10-06 10:45 UTC, yorickdowne commented on ethd
> +        || [ "${__var}" = "OBOL_CHARON_CL_ENDPOINTS" ]; then
Hmm. OK for now; I'll think on whether there's a better way

2024-10-06 11:30 UTC, cnupy commented on ethd
> +        || [ "${__var}" = "OBOL_CHARON_CL_ENDPOINTS" ]; then
OK

2024-10-06 17:55 UTC, merged