feat: :sparkles: added max peers to Reth (EL)
eth-educators/eth-docker pull request #1985
Opened 2024-11-13 21:49 UTC by victorelec14

Adds the maximum number of peers that can connect to Reth using the `EL_MAX_PEER_COUNT`` variable of the .env

docs: https://reth.rs/cli/reth/node.html?highlight=MAX_OUTBOUND_PEERS#reth-node

```txt
--max-outbound-peers <MAX_OUTBOUND_PEERS>
          Maximum number of outbound requests. default: 100
```

2024-11-14 02:21 UTC, yorickdowne requested changes

2024-11-14 02:21 UTC, yorickdowne commented on reth.yml
> +      - ${EL_MAX_PEER_COUNT:-50}
Please do set that to the default that the Reth team recommends, that is, 100. Users can always reduce the amount of peers they want by setting this variable in `.env`

2024-11-14 12:32 UTC, victorelec14 reviewed
its done :)

2024-11-15 03:12 UTC, yorickdowne approved these changes
Thanks for this!

2024-11-15 03:17 UTC, merged