support multiple consensus nodes in nimbus-vc
eth-educators/eth-docker pull request #1988
Opened 2024-11-16 04:44 UTC by b0a7

pass CL_NODE into script, parse in script

2024-11-17 01:45 UTC, yorickdowne commented
This is already supported by `VC_EXTRAS` for Nimbus. `.env` documents this:
"For Nimbus VC client, put the first beacon node here, and use VC_EXTRAS for additional."

Do you see a significant UX improvement by parsing comma-separated for the user, instead?

2024-11-17 02:14 UTC, b0a7 commented
> This is already supported by `VC_EXTRAS` for Nimbus. `.env` documents this: "For Nimbus VC client, put the first beacon node here, and use VC_EXTRAS for additional."
> 
> Do you see a significant UX improvement by parsing comma-separated for the user, instead?

IMO it is nice to set it up in the same way in the .env for different validator clients.

2024-11-17 02:29 UTC, b0a7 commented
To elaborate, personally I had used Teku VC before w eth-docker, so I was accustomed to putting the comma separated list of nodes in CL_NODE.  I made this PR because I got an error when I tried to do the same while setting up a new Nimbus VC node.  I didn't notice the adjacent comment in the .env file about Nimbus to be honest.  At the same time though, without seeing the underlying technical reason for why Nimbus VC is setup differently currently (ie the slight difference in how the endpoints are passed to the VCs), naively I don't think the eth-docker user would have reason to expect there to be different ways of doing the same thing between different clients

2024-11-17 03:24 UTC, yorickdowne requested changes
This looks good. One style change please: Could you make it `__nodes` and `__node` please. I am trying to switch to a style where `UPPERCASE` is something external to the script, like a var in `.env`, and `__lowercase` are variables local to the script

2024-11-17 03:26 UTC, yorickdowne commented
BTW linting: Check out `CONTRIBUTING.md`, we have a pre-commit hook that makes this so much easier to lint on local commit

2024-11-17 14:20 UTC, b0a7 commented
> This looks good. One style change please: Could you make it `__nodes` and `__node` please. I am trying to switch to a style where `UPPERCASE` is something external to the script, like a var in `.env`, and `__lowercase` is a variable local to the script

done https://github.com/eth-educators/eth-docker/pull/1988/commits/c3aadd5086c1d7ee6d2a184726d7fc8b4a66e5ac
double checking, is test-lodestar the right label and not nimbus?

2024-11-18 04:13 UTC, yorickdowne approved these changes
Thank you for this!

2024-11-18 04:52 UTC, merged